---
# This playbook installs and enables IIS on Windows hosts
- name: Install IIS
  hosts: all
  tasks:
    - name: Install IIS
      remote_user: administrator
      remote_password: (r(AR7NDHZ6yOTjmHWgyH;zQa)=M?ix8
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
