---
# This playbook installs and enables IIS on Windows hosts

- name: Install IIS
  hosts: 34.253.204.252
  remote_user: administrator
  become: yes
  gather_facts: false
   tasks:
  - name: ping
    ping:
  
