---
- hosts: all
  gather_facts: yes
  remote_user: centos
  become: yes
  tasks:
    
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - debug: var=hostvars[inventory_hostname]['gateway']['address']
    - debug: 
        msg: "{{ansible_hostname}}"
    - debug: 
        msg: "{{ansible_all_ipv4_addresses}}"
    
    - name: Ensure hostname is in /etc/hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        regexp="^{{ ansible_default_ipv4.address }}.+$"
        line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    
    - name: Ensure hostname is in /etc/hostname
      lineinfile:
        state=present
        dest=/etc/hostname
        regexp="^{{ ansible_hostname }}"
        line="{{ ec2_tag_Name }}"

    - name: Installation de vim
      yum:
        name:
          - vim
