---

- hosts: ec2_private_ip_address
  remote_user: centos
  become: yes

  tasks:
    - name: Change the hostname to our standard
      hostname:
        name="{{ ec2_tag_Name }}"
      when:
        ansible_fqdn != ansible_ssh_host

    - name: restart machine
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: True
      when:
        reboot is defined

    - name: Waiting for server to come back up
      local_action: wait_for host="{{ec2_private_ip_address}}" port=22 state=started

    - name: Fix /etc/hostname removing the old hostname
      tags:
        - hostname
      lineinfile:
        state=present
        dest=/etc/hostname
        line="{{ ansible_default_ipv4.address }} {{ ec2_tag_Name }} {{ ansible_hostname }}"
        regexp="^{{ec2_tag_Name}}"
      when:
        ansible_fqdn != ec2_tag_Name

    - name: Validate ansible_fqdn == ec2_tag_Name
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == ec2_tag_Name