---
- hosts: all
  gather_facts: True
  remote_user: centos
  become: True
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']['gateway']
    - debug: var="{{ansible_hostname}}"
    
    - name: Ensure hostname is in /etc/hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        regexp="^{{ ansible_default_ipv4.address }}.+$"
        line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
