---
- hosts: all
  gather_facts: yes
  remote_user: centos
  become: yes
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv6']['address']
