---
- hosts: all
  remote_user: centos
  become: yes
  
  tasks:
    
    ###################
    # Time management
    ###################
    
    - name: Install NTP
      yum:
        name:
          - epel-release
          - ntp 
          - vim
         
    - name: Start the ntp service
      service: name=ntp state=started enabled=true

    
